---
# Algemeen playbook voor alle standaard zaken
- hosts: localhost
  connection: local

  tasks:
    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600

    - name: "Ensure required packages are installed"
      apt:
        name: "{{ packages }}"      
      vars:
        packages:
        - docker.io
        - docker-compose
        - molly-guard

    - name: "Ensure docker data dir is present"
      file:
        path: /opt/docker
        state: directory

    - name: "Docker settings"
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "data-root": "/opt/docker_root/",
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            },
            "default-address-pools": [
              {
                "base": "100.64.0.0/16", "size": 24
              }
            ]
          }