---
# Algemeen playbook voor alle standaard zaken
- hosts: localhost
  connection: local

  tasks:
    - name: Upgrade the APT cache and upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
        cache_valid_time: 3600

    - name: "Ensure required packages are installed"
      apt:
        name: "{{ packages }}"      
      vars:
        packages:
        - docker.io
        - docker-compose
        - molly-guard
        - joe
        - nano
        - openssh-server
        - sudo

    - name: Identify username associated with UID 1000
      command: "id -nu 1000"
      register: user_discovery
      changed_when: false
      failed_when: user_discovery.rc != 0
      ignore_errors: false

    - name: Add the discovered user to the docker and sudo group
      user:
        name: "{{ user_discovery.stdout }}"
        groups:
          - docker
          - sudo
        append: true
      register: user_mod

    # - name: "Ensure docker data dir is present"
    #   file:
    #     path: /opt/docker
    #     state: directory

    - name: "Docker settings"
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            },
            "default-address-pools": [
              {
                "base": "100.64.0.0/16", "size": 24
              }
            ]
          }
      notify: Restart Docker
  handlers:
    - name: Restart Docker
      service:
        name: docker
        state: restarted 