---
# Algemeen playbook voor alle standaard zaken
- hosts: localhost
  connection: local

  # Let op; het huidige systeem IP adres wordt toegevoegd aan de docker config.
  # Het doel hiervan is om lokaal te kunnen praten tegen de registry zonder dat
  # deze SSL ingeschakeld moet hebben.

  # Mocht het adres veranderen kan je dit playbook opnieuw starten:
  #   ansible-playbook install.yaml

  tasks:
    - name: Update APT cache en geinstalleerde software
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
        cache_valid_time: 3600

    - name: Installeer alle benodigde software
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - docker.io
          - docker-compose
          - molly-guard
          - joe
          - nano
          - openssh-server
          - sudo

    - name: Haal username op van het account gemaakt in de OS installatie
      command: "id -nu 1000"
      register: user_discovery
      changed_when: false
      failed_when: user_discovery.rc != 0
      ignore_errors: false

    - name: Voeg initiele user toe aan groep Docker
      user:
        name: "{{ user_discovery.stdout }}"
        groups:
          - docker
          - sudo
        append: true
      register: user_mod

    - name: Zorg dat /opt/docker bestaat
      file:
        path: /opt/docker
        state: directory

    - name: Haal IP adres op
      shell: hostname -I | cut -d ' ' -f 1
      register: system_ip

    - name: Zet docker configuratie goed
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "insecure-registries": ["{{ system_ip.stdout | trim }}:3000"],
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            },
            "default-address-pools": [
              {
                "base": "100.64.0.0/16", "size": 24
              }
            ]
          }
      notify: Restart Docker

  handlers:
    - name: Restart Docker
      service:
        name: docker
        state: restarted
